"""Public Python API backed by the NAVLens Rust core."""

from ._native import (
    AssetClass,
    BacktestMetrics,
    BacktestObservation,
    CurrencyCode,
    DatedDecimalReturn,
    HoldingPosition,
    IntervalMetrics,
    MarketDate,
    ModelDescriptor,
    NavlensValidationError,
    PortfolioReturnEstimate,
    PredictionRequest,
    PriceAdjustment,
    PriceObservation,
    ReturnPrediction,
    SecurityPriceObservation,
    SecurityPriceSeries,
    UnitPrice,
    UtcTimestamp,
    calculate_price_returns,
    create_return_prediction,
    estimate_portfolio_return,
    evaluate_backtest,
)
from .datasets import (
    HoldingDatasetError,
    HoldingSnapshot,
    SecurityPriceDatasetError,
    SecurityPriceSnapshot,
    select_latest_holdings_snapshot,
    select_security_price_snapshots,
)
from .sources import (
    CsvHoldingsSourceError,
    CsvSecurityPriceSourceError,
    read_holdings_snapshots,
    read_security_prices_csv,
)

__all__ = [
    "AssetClass",
    "BacktestMetrics",
    "BacktestObservation",
    "CsvHoldingsSourceError",
    "CsvSecurityPriceSourceError",
    "CurrencyCode",
    "DatedDecimalReturn",
    "HoldingDatasetError",
    "HoldingPosition",
    "HoldingSnapshot",
    "IntervalMetrics",
    "MarketDate",
    "ModelDescriptor",
    "NavlensValidationError",
    "PortfolioReturnEstimate",
    "PredictionRequest",
    "PriceAdjustment",
    "PriceObservation",
    "ReturnPrediction",
    "SecurityPriceDatasetError",
    "SecurityPriceObservation",
    "SecurityPriceSeries",
    "SecurityPriceSnapshot",
    "UnitPrice",
    "UtcTimestamp",
    "calculate_price_returns",
    "create_return_prediction",
    "estimate_portfolio_return",
    "evaluate_backtest",
    "read_holdings_snapshots",
    "read_security_prices_csv",
    "select_latest_holdings_snapshot",
    "select_security_price_snapshots",
]
