"""Public Python API backed by the NAVLens Rust core."""

from ._native import (
    AssetClass,
    BacktestMetrics,
    BacktestObservation,
    DatedDecimalReturn,
    HoldingPosition,
    IntervalMetrics,
    MarketDate,
    ModelDescriptor,
    NavlensValidationError,
    PortfolioReturnEstimate,
    PredictionRequest,
    PriceObservation,
    ReturnPrediction,
    UnitPrice,
    UtcTimestamp,
    calculate_price_returns,
    create_return_prediction,
    estimate_portfolio_return,
    evaluate_backtest,
)
from .datasets import (
    HoldingDatasetError,
    HoldingSnapshot,
    select_latest_holdings_snapshot,
)
from .sources import CsvHoldingsSourceError, read_holdings_snapshots

__all__ = [
    "AssetClass",
    "BacktestMetrics",
    "BacktestObservation",
    "CsvHoldingsSourceError",
    "DatedDecimalReturn",
    "HoldingDatasetError",
    "HoldingPosition",
    "HoldingSnapshot",
    "IntervalMetrics",
    "MarketDate",
    "ModelDescriptor",
    "NavlensValidationError",
    "PortfolioReturnEstimate",
    "PriceObservation",
    "PredictionRequest",
    "ReturnPrediction",
    "UtcTimestamp",
    "UnitPrice",
    "calculate_price_returns",
    "create_return_prediction",
    "estimate_portfolio_return",
    "evaluate_backtest",
    "read_holdings_snapshots",
    "select_latest_holdings_snapshot",
]
