from collections.abc import Sequence

class NavlensValidationError(ValueError): ...

class PortfolioReturnEstimate:
    @property
    def estimated_return_decimal(self) -> float: ...

    @property
    def estimated_return_percent(self) -> float: ...

class MarketDate:
    def __init__(self, year: int, month: int, day: int) -> None: ...
    def __str__(self) -> str: ...

class UtcTimestamp:
    def __init__(self, unix_seconds: int) -> None: ...
    @property
    def unix_seconds(self) -> int: ...

class ModelDescriptor:
    def __init__(self, name: str, version: str, feature_set_version: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def feature_set_version(self) -> str: ...

class PredictionRequest:
    def __init__(
        self,
        fund_id: str,
        prediction_date: MarketDate,
        target_date: MarketDate,
        generated_at: UtcTimestamp,
        data_as_of: UtcTimestamp,
    ) -> None: ...
    @property
    def fund_id(self) -> str: ...
    @property
    def prediction_date(self) -> MarketDate: ...
    @property
    def target_date(self) -> MarketDate: ...
    @property
    def generated_at(self) -> UtcTimestamp: ...
    @property
    def data_as_of(self) -> UtcTimestamp: ...

class ReturnPrediction:
    @property
    def expected_return(self) -> float: ...
    @property
    def lower_bound(self) -> float: ...
    @property
    def upper_bound(self) -> float: ...
    @property
    def confidence_level(self) -> float: ...
    @property
    def model(self) -> ModelDescriptor: ...

def estimate_portfolio_return(
    components: Sequence[tuple[float, float]],
    daily_expense_rate: float = ...,
) -> PortfolioReturnEstimate: ...

def create_return_prediction(
    expected_return: float,
    lower_bound: float,
    upper_bound: float,
    confidence_level: float,
    model: ModelDescriptor,
) -> ReturnPrediction: ...
