from collections.abc import Sequence

class NavlensValidationError(ValueError): ...

class PortfolioReturnEstimate:
    @property
    def estimated_return_decimal(self) -> float: ...

    @property
    def estimated_return_percent(self) -> float: ...

class MarketDate:
    def __init__(self, year: int, month: int, day: int) -> None: ...
    def __str__(self) -> str: ...

class UnitPrice:
    def __init__(self, value: float) -> None: ...
    @property
    def value(self) -> float: ...

class PriceObservation:
    def __init__(self, date: MarketDate, unit_price: UnitPrice) -> None: ...
    @property
    def date(self) -> MarketDate: ...
    @property
    def unit_price(self) -> UnitPrice: ...

class DatedDecimalReturn:
    @property
    def date(self) -> MarketDate: ...
    @property
    def return_decimal(self) -> float: ...

class UtcTimestamp:
    def __init__(self, unix_seconds: int) -> None: ...
    @property
    def unix_seconds(self) -> int: ...

class ModelDescriptor:
    def __init__(self, name: str, version: str, feature_set_version: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def feature_set_version(self) -> str: ...

class PredictionRequest:
    def __init__(
        self,
        fund_id: str,
        prediction_date: MarketDate,
        target_date: MarketDate,
        generated_at: UtcTimestamp,
        data_as_of: UtcTimestamp,
    ) -> None: ...
    @property
    def fund_id(self) -> str: ...
    @property
    def prediction_date(self) -> MarketDate: ...
    @property
    def target_date(self) -> MarketDate: ...
    @property
    def generated_at(self) -> UtcTimestamp: ...
    @property
    def data_as_of(self) -> UtcTimestamp: ...

class ReturnPrediction:
    @property
    def expected_return(self) -> float: ...
    @property
    def lower_bound(self) -> float: ...
    @property
    def upper_bound(self) -> float: ...
    @property
    def confidence_level(self) -> float: ...
    @property
    def model(self) -> ModelDescriptor: ...

class BacktestObservation:
    def __init__(
        self,
        prediction_date: MarketDate,
        target_date: MarketDate,
        prediction: ReturnPrediction,
        actual_return: float,
    ) -> None: ...
    @property
    def prediction_date(self) -> MarketDate: ...
    @property
    def target_date(self) -> MarketDate: ...
    @property
    def predicted_return(self) -> float: ...
    @property
    def actual_return(self) -> float: ...

class IntervalMetrics:
    @property
    def confidence_level(self) -> float: ...
    @property
    def sample_count(self) -> int: ...
    @property
    def coverage(self) -> float: ...
    @property
    def mean_width(self) -> float: ...

class BacktestMetrics:
    @property
    def sample_count(self) -> int: ...
    @property
    def mean_absolute_error(self) -> float: ...
    @property
    def mean_error(self) -> float: ...
    @property
    def root_mean_squared_error(self) -> float: ...
    @property
    def direction_accuracy(self) -> float: ...
    @property
    def interval(self) -> IntervalMetrics | None: ...

def estimate_portfolio_return(
    components: Sequence[tuple[float, float]],
    daily_expense_rate: float = ...,
) -> PortfolioReturnEstimate: ...

def create_return_prediction(
    expected_return: float,
    lower_bound: float,
    upper_bound: float,
    confidence_level: float,
    model: ModelDescriptor,
) -> ReturnPrediction: ...

def calculate_price_returns(
    fund_id: str,
    observations: Sequence[PriceObservation],
) -> list[DatedDecimalReturn]: ...

def evaluate_backtest(
    fund_id: str,
    observations: Sequence[BacktestObservation],
) -> BacktestMetrics: ...
