from collections.abc import Sequence
from typing import Literal, TypeAlias

class NavlensValidationError(ValueError): ...

class AssetClass:
    def __init__(self, value: str) -> None: ...
    @property
    def name(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...

class HoldingPosition:
    def __init__(self, instrument_id: str, asset_class: AssetClass, weight: float) -> None: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def asset_class(self) -> AssetClass: ...
    @property
    def fund_total_weight(self) -> float: ...

class PortfolioReturnEstimate:
    @property
    def estimated_return_decimal(self) -> float: ...
    @property
    def estimated_return_percent(self) -> float: ...

class MarketDate:
    def __init__(self, year: int, month: int, day: int) -> None: ...
    def calendar_days_since(self, earlier: MarketDate) -> int: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...

class SessionKind:
    def __init__(self, value: str) -> None: ...
    @property
    def name(self) -> str: ...
    def is_open(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...

class SessionOverride:
    def __init__(self, date: MarketDate, session: SessionKind) -> None: ...
    @property
    def date(self) -> MarketDate: ...
    @property
    def session(self) -> SessionKind: ...
    def __eq__(self, other: object) -> bool: ...

class MarketCalendar:
    def __init__(self, overrides: Sequence[SessionOverride] | None = ...) -> None: ...
    def session_on(self, date: MarketDate) -> SessionKind: ...
    def next_open_date(self, date: MarketDate) -> MarketDate: ...
    def __eq__(self, other: object) -> bool: ...

class UnitPrice:
    def __init__(self, value: float) -> None: ...
    @property
    def value(self) -> float: ...

class PriceObservation:
    def __init__(self, date: MarketDate, unit_price: UnitPrice) -> None: ...
    @property
    def date(self) -> MarketDate: ...
    @property
    def unit_price(self) -> UnitPrice: ...

class CurrencyCode:
    def __init__(self, value: str) -> None: ...
    @property
    def code(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...

class CurrencyPair:
    def __init__(self, base_currency: CurrencyCode, quote_currency: CurrencyCode) -> None: ...
    @property
    def base_currency(self) -> CurrencyCode: ...
    @property
    def quote_currency(self) -> CurrencyCode: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class FxRate:
    def __init__(self, quote_currency_per_one_base_currency: float) -> None: ...
    @property
    def quote_currency_per_one_base_currency(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...

class FxRateKind:
    def __init__(self, value: str) -> None: ...
    @property
    def name(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...

class FxRateObservation:
    def __init__(
        self,
        pair: CurrencyPair,
        market_date: MarketDate,
        rate: FxRate,
        kind: FxRateKind,
    ) -> None: ...
    @property
    def pair(self) -> CurrencyPair: ...
    @property
    def market_date(self) -> MarketDate: ...
    @property
    def rate(self) -> FxRate: ...
    @property
    def kind(self) -> FxRateKind: ...
    def __eq__(self, other: object) -> bool: ...

class FxRateSeries:
    def __init__(self, observations: Sequence[FxRateObservation]) -> None: ...
    @property
    def pair(self) -> CurrencyPair: ...
    @property
    def kind(self) -> FxRateKind: ...
    @property
    def observations(self) -> list[FxRateObservation]: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class PriceAdjustment:
    def __init__(self, value: str) -> None: ...
    @property
    def name(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...

class SecurityPriceObservation:
    def __init__(
        self,
        instrument_id: str,
        market_date: MarketDate,
        price: UnitPrice,
        currency: CurrencyCode,
        adjustment: PriceAdjustment,
    ) -> None: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def market_date(self) -> MarketDate: ...
    @property
    def price(self) -> UnitPrice: ...
    @property
    def currency(self) -> CurrencyCode: ...
    @property
    def adjustment(self) -> PriceAdjustment: ...
    def __eq__(self, other: object) -> bool: ...

class SecurityPriceSeries:
    def __init__(self, observations: Sequence[SecurityPriceObservation]) -> None: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def currency(self) -> CurrencyCode: ...
    @property
    def adjustment(self) -> PriceAdjustment: ...
    @property
    def observations(self) -> list[SecurityPriceObservation]: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class DatedDecimalReturn:
    @property
    def date(self) -> MarketDate: ...
    @property
    def return_decimal(self) -> float: ...

class ReturnPeriod:
    def __init__(self, period_start_date: MarketDate, period_end_date: MarketDate) -> None: ...
    @property
    def period_start_date(self) -> MarketDate: ...
    @property
    def period_end_date(self) -> MarketDate: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PeriodDecimalReturn:
    def __init__(self, period: ReturnPeriod, return_decimal: float) -> None: ...
    @property
    def period(self) -> ReturnPeriod: ...
    @property
    def period_start_date(self) -> MarketDate: ...
    @property
    def period_end_date(self) -> MarketDate: ...
    @property
    def return_decimal(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...

class UtcTimestamp:
    def __init__(self, unix_seconds: int) -> None: ...
    @property
    def unix_seconds(self) -> int: ...

class ModelDescriptor:
    def __init__(self, name: str, version: str, feature_set_version: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def feature_set_version(self) -> str: ...

class PredictionRequest:
    def __init__(
        self,
        fund_id: str,
        prediction_date: MarketDate,
        target_date: MarketDate,
        generated_at: UtcTimestamp,
        data_as_of: UtcTimestamp,
    ) -> None: ...
    @property
    def fund_id(self) -> str: ...
    @property
    def prediction_date(self) -> MarketDate: ...
    @property
    def target_date(self) -> MarketDate: ...
    @property
    def generated_at(self) -> UtcTimestamp: ...
    @property
    def data_as_of(self) -> UtcTimestamp: ...

class ReturnPrediction:
    @property
    def expected_return(self) -> float: ...
    @property
    def lower_bound(self) -> float: ...
    @property
    def upper_bound(self) -> float: ...
    @property
    def confidence_level(self) -> float: ...
    @property
    def model(self) -> ModelDescriptor: ...

class BacktestObservation:
    def __init__(
        self,
        prediction_date: MarketDate,
        target_date: MarketDate,
        prediction: ReturnPrediction,
        actual_return: float,
    ) -> None: ...
    @property
    def prediction_date(self) -> MarketDate: ...
    @property
    def target_date(self) -> MarketDate: ...
    @property
    def predicted_return(self) -> float: ...
    @property
    def actual_return(self) -> float: ...

class IntervalMetrics:
    @property
    def confidence_level(self) -> float: ...
    @property
    def sample_count(self) -> int: ...
    @property
    def coverage(self) -> float: ...
    @property
    def mean_width(self) -> float: ...

class BacktestMetrics:
    @property
    def sample_count(self) -> int: ...
    @property
    def mean_absolute_error(self) -> float: ...
    @property
    def mean_error(self) -> float: ...
    @property
    def root_mean_squared_error(self) -> float: ...
    @property
    def direction_accuracy(self) -> float: ...
    @property
    def interval(self) -> IntervalMetrics | None: ...

class ReconciliationMetrics:
    @property
    def sample_count(self) -> int: ...
    @property
    def mean_absolute_residual(self) -> float: ...
    @property
    def mean_residual(self) -> float: ...
    @property
    def root_mean_squared_residual(self) -> float: ...
    @property
    def mean_return_coverage(self) -> float: ...
    @property
    def full_return_coverage_ratio(self) -> float: ...

def estimate_portfolio_return(
    components: Sequence[tuple[float, float]],
    daily_expense_rate: float = ...,
) -> PortfolioReturnEstimate: ...
def create_return_prediction(
    expected_return: float,
    lower_bound: float,
    upper_bound: float,
    confidence_level: float,
    model: ModelDescriptor,
) -> ReturnPrediction: ...
def calculate_price_returns(
    fund_id: str,
    observations: Sequence[PriceObservation],
) -> list[DatedDecimalReturn]: ...
def calculate_price_period_returns(
    fund_id: str,
    observations: Sequence[PriceObservation],
) -> list[PeriodDecimalReturn]: ...
def evaluate_backtest(
    fund_id: str,
    observations: Sequence[BacktestObservation],
) -> BacktestMetrics: ...
def evaluate_reconciliation_metrics(
    results: Sequence[FundReturnReconciliationResult],
) -> ReconciliationMetrics: ...

class PriceCurrencyPolicy:
    def __init__(self, value: str) -> None: ...
    @property
    def name(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...

class AlignmentPolicy:
    def __init__(
        self,
        fund_base_currency: CurrencyCode,
        required_price_adjustment: PriceAdjustment,
        pricing_as_of_date: MarketDate,
        minimum_observations: int,
        max_staleness_calendar_days: int,
    ) -> None: ...
    @property
    def fund_base_currency(self) -> CurrencyCode: ...
    @property
    def required_price_adjustment(self) -> PriceAdjustment: ...
    @property
    def pricing_as_of_date(self) -> MarketDate: ...
    @property
    def minimum_observations(self) -> int: ...
    @property
    def max_staleness_calendar_days(self) -> int: ...
    @property
    def price_currency_policy(self) -> PriceCurrencyPolicy: ...
    def with_price_currency_policy(self, policy: PriceCurrencyPolicy) -> AlignmentPolicy: ...

class SecurityPriceHistoryCandidate:
    def __init__(
        self,
        instrument_id: str,
        observations: Sequence[SecurityPriceObservation],
    ) -> None: ...
    @property
    def instrument_id(self) -> str: ...
    @property
    def observations(self) -> list[SecurityPriceObservation]: ...

CoverageGapKind: TypeAlias = Literal[
    "unsupported_asset_class",
    "missing_price_series",
    "insufficient_observations",
    "currency_mismatch",
    "incompatible_price_adjustment",
    "stale_prices",
]

class CoverageGapReason:
    @property
    def kind(self) -> CoverageGapKind: ...
    @property
    def asset_class(self) -> AssetClass | None: ...
    @property
    def observations_found(self) -> int | None: ...
    @property
    def observations_required(self) -> int | None: ...
    @property
    def expected_currency(self) -> CurrencyCode | None: ...
    @property
    def found_currency(self) -> CurrencyCode | None: ...
    @property
    def expected_price_adjustment(self) -> PriceAdjustment | None: ...
    @property
    def found_price_adjustment(self) -> PriceAdjustment | None: ...
    @property
    def latest_observation_date(self) -> MarketDate | None: ...
    @property
    def pricing_as_of_date(self) -> MarketDate | None: ...
    @property
    def max_staleness_calendar_days(self) -> int | None: ...

class CoveredHoldingPrice:
    @property
    def holding(self) -> HoldingPosition: ...
    @property
    def series(self) -> SecurityPriceSeries: ...

class UncoveredHolding:
    @property
    def holding(self) -> HoldingPosition: ...
    @property
    def reason(self) -> CoverageGapReason: ...

class PortfolioCoverageReport:
    @property
    def covered(self) -> list[CoveredHoldingPrice]: ...
    @property
    def uncovered_listed(self) -> list[UncoveredHolding]: ...
    @property
    def declared_weight(self) -> float: ...
    @property
    def covered_weight(self) -> float: ...
    @property
    def uncovered_listed_weight(self) -> float: ...
    @property
    def unrepresented_weight(self) -> float: ...
    @property
    def total_uncovered_weight(self) -> float: ...
    @property
    def coverage_ratio(self) -> float: ...
    @property
    def policy(self) -> AlignmentPolicy: ...

def align_holdings_prices(
    holdings: Sequence[HoldingPosition],
    candidates: Sequence[SecurityPriceHistoryCandidate],
    policy: AlignmentPolicy,
) -> PortfolioCoverageReport: ...

class PortfolioComponentContribution:
    @property
    def weight(self) -> float: ...
    @property
    def market_return(self) -> float: ...
    @property
    def weighted_contribution(self) -> float: ...

class ComponentContribution:
    @property
    def holding(self) -> HoldingPosition: ...
    @property
    def period_return(self) -> PeriodDecimalReturn: ...
    @property
    def contribution(self) -> PortfolioComponentContribution: ...

class PortfolioReturnContribution:
    @property
    def observed_contribution(self) -> float: ...
    @property
    def return_coverage(self) -> float: ...
    @property
    def has_full_coverage(self) -> bool: ...

ReturnCoverageGapKind: TypeAlias = Literal[
    "missing_exact_period_return",
    "missing_direct_fx_candidate",
    "fx_rate_kind_mismatch",
    "missing_fx_start_observation",
    "stale_fx_start_observation",
    "stale_fx_end_observation",
]

class ReturnCoverageGapReason:
    @property
    def kind(self) -> ReturnCoverageGapKind: ...
    @property
    def required_pair(self) -> CurrencyPair | None: ...
    @property
    def required_kind(self) -> FxRateKind | None: ...
    @property
    def available_kinds(self) -> list[FxRateKind] | None: ...
    @property
    def requested_date(self) -> MarketDate | None: ...
    @property
    def boundary_evidence(self) -> FxBoundaryEvidence | None: ...
    @property
    def maximum_staleness_calendar_days(self) -> int | None: ...

class ReturnCoverageGap:
    @property
    def holding(self) -> HoldingPosition: ...
    @property
    def reason(self) -> ReturnCoverageGapReason: ...

class ReturnContributionResult:
    @property
    def period(self) -> ReturnPeriod: ...
    @property
    def component_contributions(self) -> list[ComponentContribution]: ...
    @property
    def observed_contribution(self) -> PortfolioReturnContribution: ...
    @property
    def price_coverage(self) -> float: ...
    @property
    def price_gaps(self) -> list[UncoveredHolding]: ...
    @property
    def return_gaps(self) -> list[ReturnCoverageGap]: ...

def calculate_return_contribution(
    report: PortfolioCoverageReport,
    target_period: ReturnPeriod,
) -> ReturnContributionResult: ...

class FundReturnReconciliation:
    @property
    def published_fund_return(self) -> float: ...
    @property
    def observed_portfolio_contribution(self) -> PortfolioReturnContribution: ...
    @property
    def reconciliation_residual(self) -> float: ...

class FundReturnReconciliationResult:
    @property
    def period(self) -> ReturnPeriod: ...
    @property
    def reconciliation(self) -> FundReturnReconciliation: ...

def reconcile_fund_return(
    published_fund_return: PeriodDecimalReturn,
    contribution_result: ReturnContributionResult,
) -> FundReturnReconciliationResult: ...
def reconcile_fx_adjusted_fund_return(
    published_fund_return: PeriodDecimalReturn,
    contribution_result: FxAdjustedReturnContributionResult,
) -> FundReturnReconciliationResult: ...

class FxReturnPolicy:
    def __init__(
        self, required_fx_rate_kind: FxRateKind, max_fx_staleness_calendar_days: int
    ) -> None: ...
    @property
    def required_fx_rate_kind(self) -> FxRateKind: ...
    @property
    def max_fx_staleness_calendar_days(self) -> int: ...

class FxBoundaryEvidence:
    @property
    def requested_date(self) -> MarketDate: ...
    @property
    def observation(self) -> FxRateObservation: ...
    @property
    def staleness_calendar_days(self) -> int: ...

class FxAdjustmentEvidence:
    @property
    def required_pair(self) -> CurrencyPair: ...
    @property
    def required_kind(self) -> FxRateKind: ...
    @property
    def start(self) -> FxBoundaryEvidence: ...
    @property
    def end(self) -> FxBoundaryEvidence: ...
    @property
    def fx_return(self) -> float: ...

class CurrencyReturnAdjustment:
    @property
    def is_applied(self) -> bool: ...
    @property
    def is_not_required(self) -> bool: ...
    @property
    def applied_evidence(self) -> FxAdjustmentEvidence | None: ...

class FxAdjustedComponentContribution:
    @property
    def holding(self) -> HoldingPosition: ...
    @property
    def security_period_return(self) -> PeriodDecimalReturn: ...
    @property
    def currency_adjustment(self) -> CurrencyReturnAdjustment: ...
    @property
    def effective_base_currency_return(self) -> float: ...
    @property
    def contribution(self) -> PortfolioComponentContribution: ...

class FxAdjustedReturnContributionResult:
    @property
    def period(self) -> ReturnPeriod: ...
    @property
    def component_contributions(self) -> list[FxAdjustedComponentContribution]: ...
    @property
    def observed_contribution(self) -> PortfolioReturnContribution: ...
    @property
    def price_coverage(self) -> float: ...
    @property
    def price_gaps(self) -> list[UncoveredHolding]: ...
    @property
    def return_gaps(self) -> list[ReturnCoverageGap]: ...

def calculate_fx_adjusted_return_contribution(
    report: PortfolioCoverageReport,
    target_period: ReturnPeriod,
    fx_candidates: list[FxRateSeries],
    fx_policy: FxReturnPolicy,
) -> FxAdjustedReturnContributionResult: ...
